all: \
	$(addsuffix .str, $(basename $(wildcard iso/movie/*.mp4))) \
	$(addsuffix .str, $(basename $(wildcard iso/movie/*/*.mp4)))

# STR converts
iso/movie/%.str: iso/movie/%.mp4
	tools/psxavenc/psxavenc -t str -f 37800 -r 15 -I -b 4 -c 2 -x 2 -v v2 -F 1 $< $@

clean:
	echo "Cleaning .str files:"
	find iso -type f \( -name "*.str" \) -print -delete